### ISSUE TITLE
无法用/nbtedit 编辑实体

### ISSUE THREAD

**Issue by vocaloidkiss** [MeowCraftMC/NBTEdit#17]
无法用/nbtedit uuid
或者/nbtedit 玩家名字
编辑任何实体，玩家
会显示试图执行该命令时出现意外错误

但/nbtedit hand和/nbtedit me不受影响，可以正常编辑手中物品和自己的nbt

**Comment by vocaloidkiss** [comment]
游戏版本1.20.1，fabric

**Comment by vocaloidkiss** [comment]
希望加个debug模式，能输出模组的log

**Comment by qyl27** [comment]
模组的log在游戏的debug.log中可以看到。  
另外命令出错在聊天框里面鼠标指针放上去应该是可以看到调用栈的。  
这个问题我需要确认一下，不过近期比较忙，也欢迎pr（如果有）。

**Comment by vocaloidkiss** [comment]
Argument ' entity ' is defined as class _2300, not class net . minecraft . class _1297

**Comment by qyl27** [comment]
好的，我尽快进行修复，感谢反馈。

**Comment by vocaloidkiss** [comment]
快捷键编辑是可以正常触发的

**Comment by vocaloidkiss** [comment]
对于方块则是显示这个Argument ' block ' is defined as class _2280, not class net . minecraft . class _2338

**Comment by qyl27** [comment]
已经修复了，目前可以在 GitHub Release 页面下载 1.20.1-4.4.2 版本，其他网站正在上传。

**Comment by vocaloidkiss** [comment]
我有个小问题，就是多人游戏编辑其他玩家，发现他们的compoundtag标签没有二级标签正常吗

**Comment by vocaloidkiss** [comment]
好的，最新版作者已经修复二级标签问题，完美了

**Comment by qyl27** [comment]
是的，这是我说的发现的另一个问题x
