### ISSUE TITLE
即使已经修改config文件，仍然无法在多人游戏中修改其他玩家

### ISSUE THREAD

**Issue by vocaloidkiss** [MeowCraftMC/NBTEdit#19]
显示你不能编辑其他玩家

**Comment by vocaloidkiss** [comment]
版本1.20.1fabric
log信息为
[CHAT] 你不能编辑其他玩家！

**Comment by qyl27** [comment]
这个问题我未能复现，能否发一下所在多人游戏服务端上的config.json？

**Comment by vocaloidkiss** [comment]
{"canEditOthers":ture,"permissionLevel":4}

**Comment by vocaloidkiss** [comment]
[nbtedit.zip](https://github.com/qyl27/NBTEdit/files/12618675/nbtedit.zip)

**Comment by qyl27** [comment]
`ture` 拼写错误，应为 `true` 。

**Comment by qyl27** [comment]
不过我发现了另一个问题，正在推送修复。

**Comment by vocaloidkiss** [comment]
不好意思
我看了半天没看出来
马上关闭此issue

**Comment by vocaloidkiss** [comment]
超快的处理速度，爱了
