### ISSUE TITLE
无法跨物品复制

### ISSUE THREAD

**Issue by vocaloidkiss** [MeowCraftMC/NBTEdit#23]
复制了一个标签，关闭后编辑另一个物品，无法粘贴，只会粘贴出一个新建标签

**Comment by qyl27** [comment]
ah……这个问题，容我确认一下……今天在更新1.20.2……

**Comment by vocaloidkiss** [comment]
新问题，无法在第一层目录粘贴。
复制可以，因为复制是选中本层目录，复制。
但无法粘贴出来，因为粘贴选中目录后，会粘贴到选中目录的下一层

**Comment by qyl27** [comment]
是希望粘贴时候粘贴在所选tag的同级吗？  
之前设计这个功能时候考虑的是，如果选择粘贴在同级，那就没办法作为子tag粘贴到空的compound中。

**Comment by vocaloidkiss** [comment]
可以不选中就默认粘贴到第一层，其他的都可以用子tag粘贴，其实就是第一层没法粘贴

**Comment by vocaloidkiss** [comment]
现在是没选中就没有那些复制粘贴按钮，我的想法是没选中也有粘贴按钮，可以粘贴在最高层tag，选中就粘贴到子tag。

**Comment by qyl27** [comment]
综合看来的话，我觉得改进方案可以是这样：  
没有选择某个Tag时，粘贴在第一层（ROOT下面）；  
选择了一个不是容器的Tag时，粘贴在所选内容的同层；  
选择了一个容器Tag时，粘贴在所选内容的下一层。（或许也可以引入 Shift 按键，按下时粘贴在同层？）

**Comment by qyl27** [comment]
刚刚重新考虑了一下，我认为上述改进方案会造成粘贴行为不一致造成困惑。  
或许应该不允许在非容器标签上的粘贴操作，并且给出明确的提示。（也就是必须要选中一个容器才能粘贴）

**Comment by vocaloidkiss** [comment]
很不错的想法，辛苦了

**Comment by vocaloidkiss** [comment]
请问这个改动何时能实装

**Comment by qyl27** [comment]
假期之后（好不容易放个假.jpeg）

**Comment by vocaloidkiss** [comment]
嗯嗯

**Comment by qyl27** [comment]
已经完成了，在1.20.1-5.0.0中。  
当所选内容不支持该操作的时候不显示按钮，使用快捷键会听到村民拒绝的声音。

**Comment by vocaloidkiss** [comment]
👌
