### ISSUE TITLE
About 1.20.3+

### ISSUE THREAD

**Issue by vico93** [MeowCraftMC/NBTEdit#26]
Sorry about the question, but is there any updates for 1.20.3 and 1.20.4 on the radar?

This mod is really useful!

**Comment by qyl27** [comment]
Yes, and soon.

**Comment by qyl27** [comment]
I have published 1.20.3 for Fabric and NeoForge today.  
Forge 1.20.3 is not working in architectury loom for now.  [architectury/architectury-loom#191](https://github.com/architectury/architectury-loom/issues/191)

**Comment by qyl27** [comment]
NBTEdit for 1.20.3/1.20.4 (Fabric/NeoForge) was published in Modrinth and CurseForge now!
