### ISSUE TITLE
[1.20.1] [SMP] 'Exception in server tick loop' on server-side

### ISSUE THREAD

**Issue by ptk2003** [MeowCraftMC/NBTEdit#27]
When any player join to world server crashed.

Forge 47.2.19
nbtedit-forge-5.0.1
[crash-2024-02-03_15.04.04-server.txt](https://github.com/qyl27/NBTEdit/files/14151367/crash-2024-02-03_15.04.04-server.txt)

**Comment by qyl27** [comment]
Fixed in NBTEdit Forge 5.0.2 for 1.20.1.

**Comment by ptk2003** [comment]
thank you, work fine
