### ISSUE TITLE
无法修改256字符以上的nbt数据

### ISSUE THREAD

**Issue by tzhx12** [MeowCraftMC/NBTEdit#28]
例如：
修改Mine and Slash中带nbt的物品，其物品nbt常常高出256字符，编辑时会出现数据显示不全的情况，修改同理，超出256字符的将丢失
![图片001](https://github.com/qyl27/NBTEdit/assets/122715481/ad23f2af-8124-442f-bbbe-2740a127bc9f)
![图片](https://github.com/qyl27/NBTEdit/assets/122715481/09a1ac74-4a88-4eba-80da-7d4759013213)
![图片](https://github.com/qyl27/NBTEdit/assets/122715481/fc746be1-aa50-4a66-8ef1-fa3fe5964684)
![图片](https://github.com/qyl27/NBTEdit/assets/122715481/56fd0fb3-fb8f-4913-84f3-1cac4090cb9c)
minecraft版本：1.20.1
forge版本：47.2.20
NBTEdit版本：5.0.2

**Comment by qyl27** [comment]
是这样的，我此前没有想过NBT数据会那么长，已经在 `5.0.3+mc1.20.1` 修复。
