### ISSUE TITLE
NBTEDIT does not edit the nbtdata of items in hand 1.18.2

### ISSUE THREAD

**Issue by DeveloperNoShinigami** [MeowCraftMC/NBTEdit#30]
I have been unable to create an alternate id tag for the weapon but it erases upon saving. Why is that?

**Comment by qyl27** [comment]
In each ItemStack, the `id` tag should have only one.  
If you want to edit it, maybe you will change the existing one.

**Comment by DeveloperNoShinigami** [comment]
I manage to give the item an additional od by going into the tag component
and adding the entry there and please add naming to the gui when you right
click any tab, when I hover over the icons they don't tell me what is what
and it's confusing.

**Comment by qyl27** [comment]
Oh, that was updated in newer versions.  
Maybe 1.18.2 doesn't have a backport yet.  
I will check and backport it to 1.18.2 in a week.

**Comment by DeveloperNoShinigami** [comment]
Now i have a new problem, Im unable to edit the nbt of an entity.

**Comment by qyl27** [comment]
In 1.18.2?  
Can't open the editor or can't save?  
Any errors or logs?

**Comment by DeveloperNoShinigami** [comment]
No errors at all, it allows me to attempt to edit and an entry shows. After
I save it says successful but when I open it back up the entry is gone. It
seems its "forgetting" the entry. I was having this problem before but it
was merely my approach to creating the nbt entry for the held item that was
wrong. Now it won't work for entity edits using the Same method.

**Comment by qyl27** [comment]
Have you checked your nbt struct or edit by using [Minecraft Wiki](https://minecraft.wiki/)?  
In most situations, the wrong tag will be discarded.

**Comment by DeveloperNoShinigami** [comment]
Yes, it seems creating a new compound tag doesn't work and adding an
additional ID to the root doesn't work either.

**Comment by qyl27** [comment]
Well, I will check it.

**Comment by qyl27** [comment]
I can't confirm that problem.  
I tried to edit the name or inventory of an entity, and it worked.  
Btw, if you change the id of an entity, it won't work, because the entity with the previous id is already in Minecraft world.

**Comment by qyl27** [comment]
> I manage to give the item an additional od by going into the tag component and adding the entry there and please add naming to the gui when you right click any tab, when I hover over the icons they don't tell me what is what and it's confusing.

For this, I have released 1.18.2-5.1.1 for it.

**Comment by DeveloperNoShinigami** [comment]
Awesome! Also, the intention I had was to give the entity an additional ID
for example I would create a tab component then include a new ID called id2
with a value of name.

**Comment by qyl27** [comment]
Yes, you can, but if no code reads and saves it, it will be discarded also.

**Comment by DeveloperNoShinigami** [comment]
Can you provide an example of you making an additional ID on a villager?

**Comment by qyl27** [comment]
But which mod reads the `id2` tag?

**Comment by DeveloperNoShinigami** [comment]
Epicfight, since it seems to read the mod I'd, my theory is that it would
look for the id of what ever I mentioned in the datapack.  I used this mod
to make the epicfightnbt work by creating an additional ID and that worked
so i should be able to replicate that process by making a datapack that
points to the secons ID of the mob I wanna edit. The intention here is to
choose which mobs are effected by epicfight rather than all of them.

**Comment by qyl27** [comment]
Oh, have you ever understood how NBT works or read Minecraft Wiki carefully?  
Actually, the compound is a data structure like a map, which means you can't have two tags with the same name in a compound.

**Comment by DeveloperNoShinigami** [comment]
I did and the name of the compound I used was different as there was no
compound called tag inside of the villager nbt data.

**Comment by qyl27** [comment]
Maybe you should create a compound named `tag`(case sensitive).

**Comment by qyl27** [comment]
After a long time without a response, I will close it, if you have further questions, feel free to re-open this issue or create a new one.
