### ISSUE TITLE
About 1.20.5 and its replacement of NBT by the new component system

### ISSUE THREAD

**Issue by vico93** [MeowCraftMC/NBTEdit#31]
Basically, from what i've understand, in [1.20.5](https://minecraft.wiki/w/Java_Edition_1.20.5) the NBT data will be replaced by, according to wiki, "structured components".

Its most as a curiosity question, but, if you still have interest in maintaining the mod, how this can impact NBTEdit as well. Would it turn into "In-game ComponentEdit"?

**Comment by qyl27** [comment]
Sure! As far as I know, the data storage format of the component is also NBT, so NBTEdit will support it without a major break.  
I will try to improve the editor for UUID, raw json text, maybe we can have more types of editor instead of just text.

**Comment by vico93** [comment]
Thanks for the update! Looking forward the next update!

**Comment by qyl27** [comment]
The version for 1.20.6 was released.
