### ISSUE TITLE
Suggestion : Player in survivale wont be able to edit the nbt.

### ISSUE THREAD

**Issue by AmibeSkyfy16** [MeowCraftMC/NBTEdit#32]
Survival player can only show and copy the nbt on a nice GUI, no edit

**Comment by qyl27** [comment]
Are you mean a read-only gui for some players who has no permission to edit? 
But I can't imagine the actual scenario, could you have a detailed description?

**Comment by AmibeSkyfy16** [comment]
It would be nice, to see the nbt tag and to be able to copy it in a survival minecraft server. Just because im curious on certains stats... Of course if player is in survival, it is logic he cant edit, otherwise he could got an mending enchant or anything for free and it would be cheats

**Comment by qyl27** [comment]
This mod was designed as an admin tool originally, and in some situation, NBT shouldn't be shown to players.  
How about create a permission node for it?

**Comment by AmibeSkyfy16** [comment]
Yeah i understand that. Implementing a permission node is a lot of work no ? So otherwise, like it's a mod for server admin and server creator, it would make sense to not allow player who are not OP to edit nbt right ? 

Sry for that so bad english Xd

**Comment by qyl27** [comment]
Forge has provided a PermissionAPI for that, no lots of work. I will provide a configuration to let server owner decide whether allow players to view NBT or not. Is that ok?

**Comment by AmibeSkyfy16** [comment]
Ok, looks good
