### ISSUE TITLE
添加mod后崩溃

### ISSUE THREAD

**Issue by ygabzddkt** [MeowCraftMC/NBTEdit#35]
版本:1.20.6
Fabric API:0.100.0+1.20.6
mod版本:5.2.3
崩溃报告
[crash-2024-06-16_22.15.05-client.txt](https://github.com/user-attachments/files/15858664/crash-2024-06-16_22.15.05-client.txt)

**Comment by qyl27** [comment]
问题源于 FabricMC/fabric-loom#1044 ，现已发布修复的 5.2.4 版本。
