### ISSUE TITLE
crashj

### ISSUE THREAD

**Issue by vocaloidkiss** [MeowCraftMC/NBTEdit#36]
i have no idea about this crash

**Comment by vocaloidkiss** [comment]
[错误报告-2024-6-21_1.35.22.zip](https://github.com/user-attachments/files/15917808/-2024-6-21_1.35.22.zip)

**Comment by qyl27** [comment]
啊，是的，这是来自上游 FabricMC/fabric-loom#1044 的问题。

**Comment by qyl27** [comment]
在 5.2.2+mc1.20.4 修复。
