### ISSUE TITLE
Scrolling bug with entities with lots of attributes

### ISSUE THREAD

**Issue by vico93** [MeowCraftMC/NBTEdit#37]
If i try to edit an entity with lots of attributes (like wandering traders), everytime i try to click in an atribute to edit the scroll bar goes to the bottom and i cant edit anything. Also the mouse scroll doesnt work to go up or down the attributes list.

**Comment by qyl27** [comment]
Yes, that is a bug in user experience.  
The scroll bar should have hovered to use mouse-scroll now, that should be enhanced and will change in the next version. (A design fault, but should be useable.)  
Scrolling to the bottom is my mistake, I will check it later.

**Comment by qyl27** [comment]
Fixed in 5.2.6.  
Now you can scroll without hovering the bar.  
And it will not move anymore.  
Feel free to open issue if you have further problems.
