### ISSUE TITLE
1.21 NeoForge 无法打开编辑 GUI 

### ISSUE THREAD

**Issue by JH20100704** [MeowCraftMC/NBTEdit#38]
用指令或快捷键均无用
似乎 fabric 版的 1.21 无此问题

还有，请不要那么快得close此问题，我是个学生，没有那么多空余时间看issues

https://github.com/user-attachments/assets/60635d3e-a1bb-421b-b1fb-5a52f2f5ab8d

**Comment by JH20100704** [comment]
#6

嗯，我点击了，但没有发生任何事情

IM 在单人游戏中按 N 键，聊天说我正在编辑，但没有任何反应 ver 4.0.1

**Comment by qyl27** [comment]
无法复现，请提供游戏日志。

**Comment by qyl27** [comment]
而且 1.21 应该没有 4.0.1 的版本。

**Comment by JH20100704** [comment]
嗯，我更新了版本，似乎还是不行

**Comment by JH20100704** [comment]
Uploading Rec 0014.mp4…

**Comment by qyl27** [comment]
看上去问题无效，没有日志的话，要不你找人算一卦？

**Comment by JH20100704** [comment]
https://pan.huang1111.cn/s/VLqEYtd

**Comment by JH20100704** [comment]
录屏及日志文件

**Comment by JH20100704** [comment]
你急什么，日志这不来了

**Comment by JH20100704** [comment]
6
