### ISSUE TITLE
1.19.2 not working?

### ISSUE THREAD

**Issue by Looodon** [MeowCraftMC/NBTEdit#4]
Minecraft: 1.19.2
Forge: 43.1.27

Hey, I downloaded the mod, set the keybind to F10, I spawned a villager and looked at him, and I when I pressed the button it said "Editing Entity 24hef09f-1dc5-427d-8w41-f5949052361c" in green in the chat, but nothing happens no matter what I do. No GUI shows up.

EDIT: I even use the command /nbtedit with the entity name and nothing happened

> Mod List:

> AdditionalStructures(Rex's), AiImprovements, AppleSkin, AttributeFix, BadMobs, BetterF3, BetterModsButton, BluePrint, BuildersAddition, Cloth_Config, Collective, Companion, ConfigurableExtraMobDrops, Configured, Corpse, CreativeCore, DogsLie, DungeonCrawl, EnchantWithMob, Entity_Texture_Features, FallingTree, Flan, FriendlyGriefing, Friendsandfoes, GoblinTraders, GreekFantasy, GuardVillagers, GuideBook, HostileMobsAndGirls(HMaG), HumanCompanions, Hunterillager, ImprovedMobs, InventoryHud, InventoryProfilesNext, JEI, JourneyMap, Kiwi, KoltinForForge, Leashed, LetSleepingDogsLie, MemorySettings, ModNameToolTip, MoreOverlays, NoChatReports, NotEnoughAnimations, NoUnusedChunks, Oculus, Passthroughsigns, PingHud, PlayerRevive, PublicGuiAnnouncement, PuzzlesLib, RangedWirelessRedstone, Rubidium, RubidiumExtra, Savage_And_Ravage, Sound_Physics_Remastered, SpawnBalanceUtility, SwingThroughGrass, Tenshilib, ToolSwap, Torohealth, TownAndTowers, Xpbook

**Comment by qyl27** [comment]
Hi. Are there more detailed logs? I can not know what happened without logs. 
(If you are using it on a server, please update it to 4.0.1, I just found a mistake.)

Edit: please ensure the server is also installed this mod.
