### ISSUE TITLE
试图编辑最外层的复合标签会导致崩溃

### ISSUE THREAD

**Issue by INF32768** [MeowCraftMC/NBTEdit#41]
崩溃报告：[crash-2024-08-01_18.09.35-client.txt](https://github.com/user-attachments/files/16454601/crash-2024-08-01_18.09.35-client.txt)
具体操作：如图，双击带有红框的复合标签或对其按下Enter键将导致游戏崩溃
![image](https://github.com/user-attachments/assets/9f121191-07c3-4fe0-98ef-cd3a27e6434b)

**Comment by qyl27** [comment]
哇，是这样，一个我没想到的刁钻操作x  
在修了在修了.webp

**Comment by qyl27** [comment]
5.2.7 版本已发布。
