### ISSUE TITLE
The departure of the world when using /nbtedit hand with an empty hand

### ISSUE THREAD

**Issue by MacroVoid** [MeowCraftMC/NBTEdit#43]
When using /nbtedit, the hand with an empty hand flies out of the world. Game version 1.21.
**Log**: https://gist.github.com/MacroVoid/6295789b7390531653a90b237b034eb3
![bug](https://github.com/user-attachments/assets/e37c3b6e-2f24-4814-9d56-3694eb421f45)

**Comment by qyl27** [comment]
oh, yes, that's a bug, I will fix it, thank you.
