### ISSUE TITLE
1.21-5.2.8版本服务器使用

### ISSUE THREAD

**Issue by hotianbexuanto** [MeowCraftMC/NBTEdit#45]
问问新版本能在多人游戏使用吗，服务器内我给自己权限了。也打不开

**Comment by qyl27** [comment]
能在服务器里面使用

**Comment by hotianbexuanto** [comment]
客户端配置要改吗？

**Comment by qyl27** [comment]
如果你发现按键没有任何反应，那先考虑是服务器上没装；如果权限不足，聊天框里是会有提示的；客户端配置只对单人有用，服务器上同样有一份配置文件。
