### ISSUE TITLE
Name field too short for apotheosis affixes

### ISSUE THREAD

**Issue by joe-the-accountant** [MeowCraftMC/NBTEdit#46]
![image](https://github.com/user-attachments/assets/43cbc50d-b45f-4d2b-8015-df860fff3b2b)
![image](https://github.com/user-attachments/assets/73136a05-2cb8-42bf-b061-227729710e2a)

As shown in the images, the apotheosis affixes do not fit in the name field. Is there a method to increase the length in settings or is the limit hard coded?

**Comment by qyl27** [comment]
Which version are you using? It was already fixed in recent versions.

**Comment by joe-the-accountant** [comment]
That must be it. I'm using it in a 1.19.2 world. Version is Forge 5.1.0

**Comment by qyl27** [comment]
Oh, that is the old version years ago, I will backport it to 1.19.2 tomorrow.

**Comment by qyl27** [comment]
I have released ver 5.1.1 with mc 1.19.2 for this backport.
