### ISSUE TITLE
Seems to crash 1.21.3

### ISSUE THREAD

**Issue by wiesshund** [MeowCraftMC/NBTEdit#47]
Here are the logs.
Hard crash when you try to enter a world, even a fresh one.

[latest.log](https://github.com/user-attachments/files/17808468/latest.log)
[crash-2024-11-18_21.29.39-server.txt](https://github.com/user-attachments/files/17808475/crash-2024-11-18_21.29.39-server.txt)

**Comment by qyl27** [comment]
Have you noticed the version mismatch?  
`1.21.3` have no file versioned by `5.2.5`, but `5.2.9`.
