### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JillSwift** [MeowCraftMC/NBTEdit#7]
Using nbtedit-1.19.2-4.0.1-release.jar

**/nbtedit me**
no response at all.

**/nbtedit \<playername\>**
"unexpected error" message.

**Pressing "n" with a tile entity block**
chat notice that it is editing block, but no gui

the log:

[https://paste.ee/p/YDhpn](https://paste.ee/p/YDhpn)

**Comment by qyl27** [comment]
It should be fixed, thank you for your log and your patient.

**Comment by JillSwift** [comment]
Yes! It is fixed. the GUI now shows

**Comment by qyl27** [comment]
Ah, there is one more bug. (Can not save NBT in some situation). It needs more time for fixing.

**Comment by qyl27** [comment]
Ah, there is one more bug. (Can not save NBT in some situation). It needs more time for fixing.

**Comment by qyl27** [comment]
It fixed now, have a try?  
I have tested in 1.19.2 single and multi player mode.  
If it caused further exception, issues are welcome.

**Comment by JillSwift** [comment]
**4.03** - I tried to break it, I really did. But it worked great!
