### ISSUE TITLE
TagList cannot append any value.

### ISSUE THREAD

**Issue by ElysiumEr** [MeowCraftMC/NBTEdit#8]
MC Version 1.19.2
When TagList appended in nbt, it cannot add any value in it, every data type above is hidden,
including copy, paste and delete button are also hidden when selecting EMPTY TagList.
When selecting List that contains values, such as Lore, the specific type of values is available to append.

**Comment by qyl27** [comment]
Sorry for late response, I am out of condition for several weeks.  
Yes, the bug confirmed. I have wrote an `active` to an `inactive`.  
It was fixed in ver 1.19.2-4.0.4. (The file in Curseforge may need review by their staff, the file in Modrinth and GitHub release are ready.)
